import type { AgentTransport, PreparedAgentSession, SessionInput, WorkflowAgentMessage, WorkflowAgentSession, WorkflowAgentSessionEvent, WorkflowAgentSessionReference, WorkflowAgentSessionState } from "../src/agent-execution.js";
type TestMessage = { role: string; content?: unknown; stopReason?: string; errorMessage?: string; usage?: { input: number; output: number; cacheRead: number; cacheWrite: number; cost: { total: number } } };
type TestPiAssistantMessageEvent = NonNullable<WorkflowAgentSessionEvent["assistantMessageEvent"]> & { readonly contentIndex?: number; readonly delta?: string; readonly partial?: WorkflowAgentMessage };
export type TestPiSessionEvent = Omit<WorkflowAgentSessionEvent, "assistantMessageEvent"> & { readonly assistantMessageEvent?: TestPiAssistantMessageEvent; readonly args?: unknown; readonly result?: unknown };
export interface TestPiSession { readonly sessionId?: string; readonly sessionFile?: string; readonly reference?: WorkflowAgentSessionReference; readonly transport?: string; readonly session?: WorkflowAgentSessionReference; readonly messages: readonly TestMessage[]; getSessionStats(): { tokens: { input: number; output: number; cacheRead: number; cacheWrite: number; total: number }; cost: number }; readonly systemPrompt?: string; readonly model?: { provider: string; model?: string; id?: string }; readonly agent?: { state: { tools: readonly { name: string }[] } }; subscribe?(listener: (event: TestPiSessionEvent) => void): () => void; prompt(text: string): Promise<void>; steer?(text: string): Promise<void>; abort?(): Promise<void>; dispose(): void | Promise<void> }
function message(value: TestMessage | undefined): WorkflowAgentMessage | undefined { return value ? { role: value.role, ...(value.content === undefined ? {} : { content: value.content }), ...(value.stopReason === undefined ? {} : { stopReason: value.stopReason }), ...(value.errorMessage === undefined ? {} : { errorMessage: value.errorMessage }), ...(value.usage === undefined ? {} : { usage: value.usage }) } : undefined; }
function input(prepared: Readonly<PreparedAgentSession>): SessionInput { return { cwd: prepared.cwd, model: { ...prepared.model }, tools: [...prepared.tools], sessionLabel: prepared.sessionLabel, ...(prepared.agentDir ? { agentDir: prepared.agentDir } : {}), ...(prepared.customTools?.length ? { customTools: [...prepared.customTools] } : {}), ...(prepared.resultTool ? { resultTool: prepared.resultTool } : {}), ...(prepared.systemPrompt === undefined ? {} : { systemPrompt: prepared.systemPrompt }), systemPromptAppend: prepared.systemPromptAppend ?? "", ...(prepared.extensionFactories?.length ? { extensionFactories: [...prepared.extensionFactories] } : {}), ...(prepared.additionalSkillPaths?.length ? { additionalSkillPaths: [...prepared.additionalSkillPaths] } : {}), ...(prepared.contextFiles === undefined ? {} : { contextFiles: [...prepared.contextFiles] }), ...(prepared.resourcePolicy ? { resourcePolicy: structuredClone(prepared.resourcePolicy) } : {}), ...(prepared.options ? { options: { ...prepared.options } } : {}) }; }
function defaultResultTool(tool: SessionInput["resultTool"]): boolean {
  if (!tool) return false;
  const parameters = tool.parameters as { type?: unknown; properties?: unknown; required?: unknown; additionalProperties?: unknown };
  const properties = parameters.properties as { result?: { type?: unknown } } | undefined;
  return parameters.type === "object" && parameters.additionalProperties === false && Array.isArray(parameters.required) && parameters.required.length === 1 && parameters.required[0] === "result" && properties !== undefined && Object.keys(properties).length === 1 && properties.result?.type === "string";
}
function assistantText(value: TestMessage | undefined): string | undefined {
  const content = value?.content;
  if (!Array.isArray(content)) return undefined;
  const text = content.filter((part): part is { type: "text"; text: string } => typeof part === "object" && part !== null && (part as { type?: unknown }).type === "text" && typeof (part as { text?: unknown }).text === "string").map((part) => part.text).join("");
  return text;
}
function state(native: TestPiSession, prepared: Readonly<PreparedAgentSession>): WorkflowAgentSessionState { const tools = native.agent?.state.tools.map(({ name }) => name) ?? prepared.tools; const model = native.model?.provider && (native.model.model ?? native.model.id) ? { provider: native.model.provider, model: native.model.model ?? native.model.id ?? prepared.model.model, ...(prepared.model.thinking ? { thinking: prepared.model.thinking } : {}) } : { ...prepared.model }; return { model, ...(model.thinking ? { thinking: model.thinking } : {}), tools: [...tools], ...(native.systemPrompt === undefined ? {} : { systemPrompt: native.systemPrompt }) }; }
export function testTransport(factory: (input: SessionInput) => Promise<TestPiSession>): AgentTransport { return { id: "local", async createSession(prepared: Readonly<PreparedAgentSession>): Promise<WorkflowAgentSession> { const sessionInput = input(prepared); const native = await factory(sessionInput); let aborted = false; const reference = native.sessionId === undefined ? native.reference ?? native.session : { transport: "test", sessionId: native.sessionId, ...(native.sessionFile ? { locator: { sessionFile: native.sessionFile } } : {}) }; if (!reference) throw new Error("Test session has no reference"); return { reference: { ...reference, transport: "local" }, getState: () => state(native, prepared), getSessionStats: () => native.getSessionStats(), getLastAssistant: () => message([...native.messages].reverse().find((candidate) => candidate.role === "assistant")), subscribe(listener: (event: WorkflowAgentSessionEvent) => void) { return native.subscribe?.((event) => { listener(event); }) ?? (() => undefined); }, async prompt(text: string) { await native.prompt(text); const latest = [...native.messages].reverse().find((candidate) => candidate.role === "assistant"); if (defaultResultTool(sessionInput.resultTool) && latest && latest.stopReason !== "error" && latest.stopReason !== "aborted" && assistantText(latest) !== undefined) await sessionInput.resultTool?.execute("test-result", { result: assistantText(latest) }, new AbortController().signal, undefined, undefined as never); const assistant = message(latest); return assistant ? { assistant } : {}; }, async steer(text: string) { await native.steer?.(text); }, async abort() { if (aborted) return; aborted = true; await native.abort?.(); }, async dispose() { if (!aborted) { aborted = true; await native.abort?.(); } await native.dispose(); } }; } }; }
